default_job = "clippy"

[jobs.check]
command = [
  "cargo",
  "check",
  "--all-targets",
  "--all-features",
  "--color",
  "always",
]
need_stdout = false

[jobs.clippy]
command = [
  "cargo",
  "clippy",
  "--all-targets",
  "--all-features",
  "--color",
  "always",
]
need_stdout = false

[jobs.doc]
command = [
  "cargo",
  "doc",
  "--no-deps",
  "--document-private-items",
  "--color",
  "always",
]
need_stdout = false

[jobs.nextest]
command = [
  "cargo",
  "nextest",
  "run",
  "--all-features",
  "--hide-progress-bar",
  "--failure-output",
  "final",
  "--color",
  "always",
]
need_stdout = true

[jobs.test-fast]
command = [
  "cargo",
  "nextest",
  "run",
  "--all-features",
  "--lib",
  "--bins",
  "--hide-progress-bar",
  "--color",
  "always",
]
need_stdout = true
